# Generated by Django 6.0.1 on 2026-03-08 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aksessuar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, default='', max_length=255)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Аксессуар', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Antikompyuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, max_length=255, null=True)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Антикомп', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(blank=True, max_length=100, null=True)),
                ('user_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pdf_downloaded', models.BooleanField(default=False)),
                ('is_telegram_shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Gatoviy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(default='', max_length=255)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('filial', models.CharField(default='-', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='Готовые', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kapliya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, max_length=255, null=True)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Капля', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, default='', max_length=255)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Оправа', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('izoh', models.TextField(blank=True, default='-')),
                ('filial', models.CharField(default='-', max_length=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rangli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, max_length=255, null=True)),
                ('dioptriya', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Цветная линза', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rangsiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=50)),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, max_length=255, null=True)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Контакт линза', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=50, unique=True)),
                ('parol', models.CharField(default='', max_length=128)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('dioptriya', models.CharField(blank=True, max_length=50, null=True)),
                ('miqdor', models.IntegerField(default=0)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='optika.archive')),
            ],
        ),
    ]
